### ISSUE TITLE
See how many defaults we can have to eventually get to `bacalhau serve` as the only thing necessary

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#1139] opened 2022-11-14 18:09 UTC

**Comment by simonwo** [comment] 2023-02-21 13:34
@wjam Is this done following your work? IIRC I can run `bacalhau serve` now and it will work, right?

**Comment by wjam** [comment] 2023-02-21 13:50
Closing this as a duplicate of #1231.

**Closed by wjam** 2023-02-21 13:50 UTC
