### ISSUE TITLE
2 CIDs don't mount together

### ISSUE THREAD

**Issue by js-ts** [filecoin-project/bacalhau#506] opened 2022-08-18 11:31 UTC
simple command

`bacalhau docker run -v QmQtZKRPXehLU5JroBbzBCVdhNkgZT7m4MiSD7sUVxE3LD:/hello-cid.txt -v QmT78zSuBmuS4z925WZfrqQ1qHaJ56DQaTfyMUF7F8ff5o:/hello-world-cid.txt ubuntu ls`

<img width="950" alt="image" src="https://user-images.githubusercontent.com/79689323/185464812-36a40435-1601-4616-96d1-ceb6a7a60799.png">

<img width="952" alt="image" src="https://user-images.githubusercontent.com/79689323/185384721-b011cba0-a275-4ea0-b6b5-a6b22896bb7f.png">

<img width="951" alt="image" src="https://user-images.githubusercontent.com/79689323/185394964-a5c47abc-a81b-4720-bf66-8c6177237ec3.png">

**Comment by js-ts** [comment] 2022-08-18 12:30
```
bacalhau docker run --wait --downloa
d --gpu 1 -v QmTv8e1W4q19CvX46fBxeit3SqaSB4ERcjcJUR4UnHyDoX:/yolov5s.pt  -v QmWQAtShWCo2aSX1q8cJ5bsFNSC4qXmERfezNGA3tkcY6n:/datasets  ultralytics/yolov5:latest -- /bin/bash
 -c 'ls ../../../'
```

**Comment by lukemarsden** [comment] 2022-08-19 09:12
the error is that there's another ipfs server already running on localhost:5001, try stopping that, then running it again

**Comment by lukemarsden** [comment] 2022-08-19 09:14
would be fixed by https://github.com/filecoin-project/bacalhau/issues/496

**Comment by aronchick** [comment] 2022-08-26 00:05
Not a bug

**Closed by aronchick** 2022-08-26 00:05 UTC
