### ISSUE TITLE
Need Google Analytics across bacalhau.org, docs.bacalhau.org and get downloader

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#943] opened 2022-10-25 10:11 UTC

**Comment by binocarlos** [comment] 2022-10-27 09:04
So we already have tag manager installed on the website - the tracking ID is `G-D6NP6P151C` and I've just added the same tracking ID to the docs site.  

It will be harder to add the same tracking to `get.bacalhau.org` mainly because when doing:

`curl -sL https://get.bacalhau.org/install.sh | bash`

We are not loading HTML into a browser and so we would need to do server side tracking for this request.  The issue is `get.bacalhau.org` is hosted on github pages and there is no way of tapping into their server logs to track hits on `/install.sh`

I recommend that we move away from github pages so we can add analytics to the webserver and know how many people have downloaded `/install.sh`.

This should be a seperate issue called `move get website to somewhere we can track` - so I will close this issue as done and open another issue for that

**Closed** 2022-10-27 09:06 UTC
Labels: good first issue, help wanted
