### ISSUE TITLE
Setup Proper Filecoin Devstack

### ISSUE THREAD

**Issue by philwinder** [filecoin-project/bacalhau#561] opened 2022-09-05 10:01 UTC
Currently we have no way of testing or developing against a working Filecoin/Lotus network. @binocarlos created a temporary bash script to mock it because he had issues getting lotus to work locally.

The task is to get bac setup with a proper filecoin dev setup, and enhance the current bash script.
* [ ] Read docs, make sure it makes sense. Prefer if it was local, e.g. `bac devstack --filecoin` local, nothing global, etc. https://lotus.filecoin.io/lotus/developers/local-network/
* [ ] Kai previously had an issue with these instructions. Figure out what the issue is and fix it. Fix this, submit but report to them "this is wrong, please fix", or PR, or whatever.
* [ ] Dockerize the whole thing, so we can run with devstack, create CI jobs to keep that fresh
* [ ] Add optional parameter to devstack `--filecoin` (or something) to enable using this new container.
* [ ] Add documentation to show how to use lotus as part of the devstack
* [ ] Add code to current bash script to use this local setup (because I think there are dependencies on this script)
* [ ] Add e2e tests that use the filecoin devstack

**Comment by prashant2402** [comment] 2022-09-22 10:40
Raised the PR
https://github.com/filecoin-project/bacalhau/pull/650

**Comment by wjam** [comment] 2022-10-13 11:37
I feel that the last two items should be their own ticket, especially due to the complexity around reading the data back out of Lotus

**Comment by wjam** [comment] 2022-10-14 07:44
Last two are a duplicate of #665

**Closed** 2022-10-14 08:15 UTC
Labels: UX, Provider Onboarding
