### ISSUE TITLE
Change `bacalhau serve` so it can be run without any arguments

### ISSUE THREAD

**Issue by wjam** [filecoin-project/bacalhau#1745] opened 2023-01-23 12:13 UTC
> Would be nice if `bacalhau serve` just worked everywhere with no args. Then we could have a simple k3s-like installer (maybe with nicer UX 😉).

**Comment by lukemarsden** [comment] 2023-01-25 11:11
duplicate of #1231

**Closed by lukemarsden** 2023-01-25 11:12 UTC
