### ISSUE TITLE
M2: Job Pipelines as DAGs

### ISSUE THREAD

**Issue by lukemarsden** [filecoin-project/bacalhau#190] opened 2022-06-08 10:17 UTC
ETA: 2023Q1

Children:

- [x] https://github.com/filecoin-project/bacalhau/issues/813
- [ ] https://github.com/filecoin-project/bacalhau/issues/365

# Context

This represents the design (and notes for posterity) of a short, 2-week-ish amount of development to support rudimentary DAGs. 

This work does not include:

* Support for internal private clustering mechanisms to run frameworks like Spark, for example.
* Integration with external frameworks, like an Airflow operator.

## Use Cases

* As a data engineer, I want to be able to run pipelines that consist of multiple consecutive jobs.
* As a data engineer, I want to branch pipelines with two or more parallel jobs and then reduce the results back into a single job.
* As a data engineer, I want to scale my pipeline by fanning out with sharding

## Use Cases not Considered

* As a data engineer, I want to run complex workflows of jobs that have logic to dictate which branches run.

# Interface Design

## What does the UX look like?

Most DAGs are specified via a DSL, like Kubeflow or Airflow, or via configuration, like the many Airflow converters or Dataproc, or CI-like specifications in Github/Gitlab CI or something like DVC.

But Bacalhau, at the moment, is immutable. So DAGs can be specified by creating successive single jobs. If you wanted to create a DAG script, then you could achieve it all in bash by capturing the CID output of one job and passing it into another.

In the future, we may also want the option of passing in IPNS-like pointers or using URL inputs.

* How does that translate into a DAG spec?
* What does the spec->implementation interface look like?

# Execution Design

Punt: A job should only run if the CID is new. How do we know if this is the first run? We can't yet. Maybe leverage some IPFS-stored metadata about the job.

# Architectural Research and Decision

## Executive Summary

I propose that building DAG functionality into Bacalhau is the best option, not leveraging an external DAG management system.

The main reasons for this decision are:

* although an external manager is probably more capable, it requires a similar amount of engineering time, and
* it increases both the burden on operators (they have to run multiple systems) and the burden on us, the developers, because we would be responsible for maintaining and supporting another piece of software that we don't own

Details below.

## High Level Options

1. Leverage an orchestration platform like Airflow, build an operator that is able to control bacalhau jobs...
2. Build DAG orchestration into Bacalhau... 

... Then hide interaction with airflow/bacalhau behind an interface and expose the ability to create and manage dags in the API.

As you can see, both require hiding the implementation of the DAG and adding the ability to interact with the DAG in an API. The key difference is what has control over the DAG.

### Pros/Cons of Airflow (or equivalent)

Note that Airflow could be substituted with another solution.

**Pros:**

* Handing off control to a well-established DAG solution. 
* Probably has more functionality that we can hope to implement in Bac.

**Cons:**

* Server operator burden. We'd have to ask administrators to run and operate airflow, along with bacalhau.
* Operational burden. What about HA? What about backups? What about updates? How do we orchestrate it?
* Will have to implement a custom Airflow operator (or equivalent) to allow it to interact with the bacalhau network.

### Pros/Cons of Building Into Bacalhau

**Pros:**

* Full control, tight integration, can improve over time.
* Likely to be more robust over the long term, due to fewer external dependencies
* Less operational and server operator burden.

**Cons:**

* Probably more engineering effort, but might not be much more. (Implementing an Airflow Operator vs. implementing control of a DAG - expanded discussion below)

### Job Control

With an Airflow-like solution, if ignoring the operational aspects, you'd have to implement a mechanism to allow Airflow to interact with the Bacalhau network. If we want to continue running jobs in the same way we do now, then this basically means full control over the lifecycle of jobs. The Airflow operator would need to track the APIs, which introduces a significant maintenance burden.

With a self-built solution, we would need to do the same, but we have direct access to the job codebase so development is likely to be easier. And maintenance is also likely to be easier if it's well tested because if changes occur in the API the tests will flag the issue. I think that initial development is probably easier too, because you can bootstrap the development, rather than having to jump to an external API straight away.

**I think the self-built solution is easier.**

### DAG Creation/Curation

An Airflow-like solution probably has advanced control mechanisms and efficient, stable APIs for specifying and controlling DAGs. But Bac would still need to interact with it on an API level because I assume we don't want to expose any Airflow implementation details to the user. So we would still need a Bacalhau DAG specification to Airflow DAG specification translation layer.

With a self-built solution, we'd need to leverage a DAG library (possibly) and translate the Bac DAG spec into the chosen DAG language. Again, another translation layer. But in this case, we'd have full control over the latter, so we can pick and choose DAG libraries, or maybe not at all.

**I think the self-built solution is easier.**

### Engineering impacts of Operator Burden

With an Airflow-like solution, we probably don't want node operators to have to worry about maintaining Airflow. So that means we probably need to implement the orchestration in the bacalhau server code. Now we could orchestrate that as a long-running bacalhau job itself, which might simplify the long-running requirements, but adds complication in control (i.e. should a job be able to create/destroy other jobs?). Orchestrating as a side-by-side service to bacalhau is probably more reasonable, but we'd need to implement an orchestration system, which is probably a bad fit for bacalhau.

With a self-built solution, there would be no changes from an operator's perspective. Just run Bac as normal. Obviously, we'd still need to orchestrate the jobs, but the point is that this wouldn't be exposed to the operator.

**I prefer the self-build option, just.** In the first case you're spending engineering time building an application orchestrator. In the second you're building the DAG orchestrator. So it's probably a similar amount of engineering time, but I'd rather spend that time building a DAG, which would be core Bac functionality. I'd also rather support core DAG functionality than orchestration concerns like "why is Airflow OOM'ing?"

TODO.

* Where does the DAG execution implementation run, in the Bac server, or in a Bac job?
* How does the executor keep track of all the jobs?
* What about execution resiliency, what happens if a server dies halfway through a DAG?
* What about job resiliency, what happens if a job dies halfway through its execution?
* What about caching, how can we not run jobs that have already run?

# DAG Features

List of potential features, to be prioritised.

* Simple multi-step pipelines - e.g. input -> job 1 -> job 2 -> output
* Fan in jobs - e.g. start with two separate jobs, fan into a single job
* Fan out jobs - e.g. start with a single job, fan out to two separate jobs
* Easy data passing - e.g. use the output from the previous job
* Pipeline parameters - e.g. parameterized input data, some configuration
* Job caching - e.g. don't re-run something we already have a result for
* Pipeline triggering - e.g. run this pipeline when ... something
* Pipeline scheduling - e.g. run every day
* Failure control - e.g. retries, fail early, continue despite failures, etc.
* Asset typing - e.g. this job expects a json file, a stream, etc.
* Job sharding for a single job in the pipeline - e.g. this one job spec actually fans out
* Pipeline status - e.g. track where we currently are in a pipeline run
* Pipeline lifecycle - e.g. can inject or run certain things at certain points
* Pipeline hooks - e.g. can connect to a websocket to listen for lifecycle changes
* Logging - e.g. stream logs from all jobs in a pipeline back to user
* Monitoring - e.g. expose metrics about jobs in a pipeline
* Development & testing - e.g. local environment to run pipelines or single jobs within a pipeline, test harness
* Dynamic DAGs - e.g. create new a new DAG from within a DAG. 🤯 
* Data-driven pipelines - e.g. pipelines react to new data
* https://github.com/filecoin-project/bacalhau/issues/70

# Outstanding Questions

* Massive open question - should we support "clusters of jobs" so that existing clustering frameworks like Ray/Spark/etc. can run whatever they want, including DAGs. See https://github.com/filecoin-project/bacalhau/issues/190#issuecomment-1220935841
* How can we have a consistent endpoint that "watches" for new data? See [IPNS](https://docs.ipfs.tech/concepts/ipns/#example-ipns-setup-with-cli) and [DNSLink](https://docs.ipfs.tech/concepts/dnslink/#publish-content-path)

**Comment by wdbaruni** [comment] 2022-08-19 17:41
**Concerns**
A common use case for jobs that require a DAG are jobs the require shuffling of the data between nodes to achieve locality for a given key, such as MapReduce type of jobs that have `reduceBy` or `groupBy` operations. If we are going to support such transformations, which I believe we should, then I am concerned about reinventing the wheel here and implementing our own DAG processing framework for many reasons, including:

1. An efficient implementation would avoid or minimize persisting intermediary results on desk, and would allow nodes to stream partial results to each other over the network. In addition to that, stages in the DAG can start even when previous stages are not fully complete yet to mitigate long tail partitions.
2. Need to be fault tolerant and can mitigate nodes going bad mid-way without having to restart the whole job. This is useful for batch jobs that take hours and span several nodes. This is more critical in Bacalhau as we don't have control on when nodes leave the network
3. A lot of work has be done (and still) to improve the reliability of jobs, including hot partition mitigation, rebalancing of the shards, snapshots, and so on.
4. The more critical one is the onboarding experience, as it will help Bacalhau grow faster if we can allow users to migrate their existing workloads to Bacalhau with no or minimal code change.

**Proposal**
The main challenge we have today is that Bacalhau containers are executed in standalone and isolated mode with no network access for security and safety reasons, which prevents cross node communication that is needed to run Spark or Flink jobs.

The proposal is to evaluate running Bacalhau jobs in a cluster mode where multiple containers are created with their own private subnet that only allows limited network communication and only within these containers. This should allow us to run Spark, Flink or any other distributed processing framework out of the box.

I don't know how much of that is feasible, but worth investigating before we commit ourselves to building our own DAG.

**Possible Issues**
A main issue with the proposal is that we are running in a network with trustless nodes, and enabling network communication (even a limited one) can increase the blast radius of a malicious node. Examples could be:

A malicious node can take other nodes in the same subnet/cluster down by attacking their network bandwidth with garbage data, or occupy their CPU/Memory by faking more data to be processed

1. A malicious node can prevent jobs from succeeding by keep on failing the tasks it is assigned to. I believe this is mitigated by the framework itself (e.g. Spark's master node), but will still result in the job taking longer due to retrying the failed task on the other nodes.
2. The mitigation here falls under the reputation system that we plan to build. The additional requirement is live monitoring of nodes while running the jobs and be able to take a node out if malicious activity is detected without having to wait for the job to complete. This is easier said than done, but that's where I believe our effort and focus should be at

**Comment by lukemarsden** [comment] 2022-09-28 09:33
consider using weave net for private networking, although it does introduce determinism worries

**Comment by aronchick** [comment] 2022-11-03 17:07
@enrico - did you capture all this?

**Comment by enricorotundo** [comment] 2022-12-08 15:28
Newer Ms:

https://github.com/filecoin-project/bacalhau/issues/1183
https://github.com/filecoin-project/bacalhau/issues/1176 (duplicate of this one?)

**Comment by enricorotundo** [comment] 2023-01-02 12:38
Closing this one, superseded by the milestones linked above ☝️

**Closed by enricorotundo** 2023-01-02 12:38 UTC
Labels: milestone, starmaps
