### ISSUE TITLE
install script breaks on Mac Ventura

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#946] opened 2022-10-25 18:05 UTC
I don't know if they reset something but the install.sh now hangs on Mac M1

**Comment by wjam** [comment] 2022-10-26 08:09
Does the script work if `BACALHAU_INSTALL_DIR` is set to somewhere under `/opt`, similar to where Homebrew is installed on M1?

**Comment by aronchick** [comment] 2022-10-26 09:00
yeah, i think it's sudo on Ventura.

adding 
```
%admin          ALL = (ALL) NOPASSWD:ALL
``` 
and now i can't get a repro

**Comment by simonwo** [comment] 2022-10-26 13:50
Just finished the Ventura upgrade and it worked fine for me:

```
simon@Simons-MBP ~ % curl -sL https://get.bacalhau.org/install.sh | sh         
Your system is darwin_arm64
-e 
BACALHAU CLI is detected:
Client Version: v0.3.6
Server Version: v0.3.6
-e Reinstalling BACALHAU CLI - /usr/local/bin/bacalhau...
Getting the latest BACALHAU CLI...
Installing v0.3.6 BACALHAU CLI...
Downloading https://github.com/filecoin-project/bacalhau/releases/download/v0.3.6/bacalhau_v0.3.6_darwin_arm64.tar.gz ...
Downloading sig file https://github.com/filecoin-project/bacalhau/releases/download/v0.3.6/bacalhau_v0.3.6_darwin_arm64.tar.gz.signature.sha256 ...
Verified OK
Extracting tarball ...
NOT verifying Bin
Password:
bacalhau installed into /usr/local/bin successfully.
Client Version: v0.3.6
Server Version: v0.3.6
```

Did ask me for my password but I could type it in at the prompt. I have no diff between the sudo config before or after the upgrade. So I can't reproduce :(

**Comment by simonwo** [comment] 2022-10-27 08:34
Per https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1666805978421019?thread_ts=1666789365.416339&cid=C02RLM3JHUY:
> call off the hounds it appears it was due to bad networking

So I'll close this as wontfix, if we get more data to reproduce we can reopen.

**Closed by simonwo** 2022-10-27 08:34 UTC
